### ISSUE TITLE
feature request: label arg

### ISSUE THREAD

**Issue by shimwell** [sqlinsights/streamlit-vertical-slider#1]
Congrats on this great streamlit component.

Do you think it would be possible to add a ```label``` arg to the argument options. The regular ```st.slider``` has a ```label``` are so this would mirror the slider functionality.

**Comment by sqlinsights** [comment]
Thanks. The next release will include the label and some optimizations.

**Comment by mkleinbort-ic** [comment]
Will that release happen?

**Comment by sqlinsights** [comment]
Fixed in version 2.0.5
