### ISSUE TITLE
[Feature request] Add argumentes `on_change=` / `args=`

### ISSUE THREAD

**Issue by diogo-rossi** [sqlinsights/streamlit-vertical-slider#11]
The native [slider function](https://docs.streamlit.io/develop/api-reference/widgets/st.slider#stslider) has a couple of keyword arguments [ `on_change=` / `args=`](https://github.com/streamlit/streamlit/blob/bddd5e81958eaa95aa390747e6d1b52d757aecd2/lib/streamlit/elements/widgets/slider.py#L344-L345)

Can they be added to vertical slider?

**Comment by sqlinsights** [comment]
@Diogo-Rossi AFAIK Streamlit custom components api doesnt allow callbacks.

**Comment by PaulRosenfield** [comment]
@Diogo-Rossi Streamlit has just enabled on_change callbacks for custom components: https://github.com/benjamin-awd/streamlit/commit/ad7f3d8055cdfcee9472836120b5138463007f20. I request that this issue be re-opened.
