### ISSUE TITLE
feature request: supporting tuple of values

### ISSUE THREAD

**Issue by shimwell** [sqlinsights/streamlit-vertical-slider#2]
Thanks for making the awesome widget.

I'm just trying to switch my regular streamlit sliders over to this and noticed that the ```default_value``` arg replaces the ```value``` arg and additionally unlike the slider value arge the ```default_value``` does not support a tuple of values.

Would it be worth considering supporting two values so that ranges can be accepted like they are in slider?
![Screenshot from 2022-12-08 13-05-51](https://user-images.githubusercontent.com/8583900/206454254-52604b3b-31b1-4b8e-bd26-0b65ee632812.png)

**Comment by sqlinsights** [comment]
That is intentional since this is a slider not a discreet slider. Discreet slider are for ranges while this one is for single value. Like the difference between the native st.slider and st.select_slider

**Comment by shimwell** [comment]
ah yes fair enough, I guess I'm after a non discreet vertical slider which doesn't exist at the moment. Thanks for the rapid responses.

Closing this issue as it is out of the scope of this package
