### ISSUE TITLE
Height change

### ISSUE THREAD

**Issue by hyshandler** [sqlinsights/streamlit-vertical-slider#3]
Firstly, thanks for building this! I’m wondering if there’s a way to change the height of the bar? Also, is there a way to add a second point on the slider (to select a range)?

Thanks in advance!

**Comment by acambray** [comment]
This would be great! 

Can I suggest that the height of the bar is either configurable in absolute px value or able to adapt to the height of the container?

**Comment by mianen** [comment]
This would be awesome and something I really need to make my application user friendly. Are you currently thinking about working on this update or not?

**Comment by sqlinsights** [comment]
Fixed in version 2.0.5
