### ISSUE TITLE
Colors incompatible with Streamlit's dark mode

### ISSUE THREAD

**Issue by Arepo** [sqlinsights/streamlit-vertical-slider#4]
I'm not sure as of when, but Streamlit has an auto-dark mode feature. When that's enabled the numbers describing the max and min values of the vertical sliders turn virtually invisible.

Also, those colors are very hard to edit via the CSS. I tried to hack them into submission with the following code in my streamlit application file:

```
css = """
<style>
    span {
        color: red !important;
    }
    span.MuiSlider-markLabel {
        color: white !important;
    }

</style>
"""

# Inject CSS into the app
st.markdown(css, unsafe_allow_html=True)
```

(the generic span edit just to confirm that the style tag was being picked up and it was)

But for whatever reason, the`MuiSlider-markLabel` elements don't register it (as in, it's not getting overridden, they just don't show it in their Chrome console list of css priorities)

**Comment by sqlinsights** [comment]
Fixed in version 2.0.5
