### ISSUE TITLE
streamlit-toggle not in requirements

### ISSUE THREAD

**Issue by beryder** [sqlinsights/streamlit-vertical-slider#6]
Just testing this out, and I had to pip install streamlit-toggle for the package to work

**Comment by lorepirri** [comment]
@sqlinsights I think there is an import that is not used

https://github.com/sqlinsights/streamlit-vertical-slider/blob/737b6a88c1bbd55b157a49ed40ba133a81b20e8a/streamlit_vertical_slider/__init__.py#L6

`sts` is never used, and neither `streamlit_toggle`, in the project

https://github.com/search?q=repo%3Asqlinsights%2Fstreamlit-vertical-slider%20sts&type=code

https://github.com/search?q=repo%3Asqlinsights%2Fstreamlit-vertical-slider%20streamlit_toggle&type=code

also, @beryder there are two projects that export `streamlit_toggle`:

1. `streamlit-toggle` https://pypi.org/project/streamlit-toggle/
2. and `streamlit-toggle-switch` (from the same author of `streamlit-vertical-slider`, therefore I suspect it should be this one) https://pypi.org/project/streamlit-toggle-switch/

if you `pip install streamlit-toggle` you would be using this other one: https://pypi.org/project/streamlit-toggle/

**Comment by sqlinsights** [comment]
Good catch. This must have been from a previous project. I'll clean it up and tag you in the release. Thanks!

**Comment by lorepirri** [comment]
> Good catch. This must have been from a previous project. I'll clean it up and tag you in the release. Thanks!

Thank you! I've opened PR #9 for that :)

**Comment by diogo-rossi** [comment]
I got the same issue.

Following the observation of @lorepirri, I solve my problem by just adding an empty file `streamlit_toggle.py` in my script foder.

As `streamlit_toggle` is never used anyway, this prevents the import error.

**Comment by sqlinsights** [comment]
Merged PR #9 from @lorepirri .  New Release coming soon. Thanks
