### ISSUE TITLE
Adding list of values for slider as in st.select_slider

### ISSUE THREAD

**Issue by mr-d3falt** [sqlinsights/streamlit-vertical-slider#8]
Is there a way to add to this slider options as list ? As in st.select_slider("Value:",options=[1,5,90])

**Comment by sqlinsights** [comment]
This is a continuous slider; that behavior is for a discrete slider, which has a totally different structure.

**Comment by mr-d3falt** [comment]
@sqlinsights  Is it possible to rewrite the vertical slider to discrete slider ?
